# renovate: datasource=github-tags depName=balena-io-experimental/browser versioning=loose
ARG BROWSER_VERSION=2.7.0
FROM bh.cr/balenalabs/browser-%%BALENA_ARCH%%/$BROWSER_VERSION AS base

RUN install_packages cec-utils tini

COPY start.sh /usr/src/app/start_custom.sh

RUN chmod +x /usr/src/app/start_custom.sh

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/src/app/start_custom.sh"]
